# -*- coding: utf-8 -*-
"""bounding_box_finder.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-pc_YReKxzDf_IB0ZHwqb4OD78WUGOEJ
"""

# Install torch, clone yolov5 model, other useful libraries

!pip install torch 
import torch 
from IPython.display import Image #this is to render predictions


!git clone https://github.com/ultralytics/yolov5

# Install requirements of yolov5
!pip install -r /content/yolov5/requirements.txt

# Detect
!python detect.py --source /content/drive/MyDrive/people_data/Augmented-torch --weights /content/drive/MyDrive/data/weightE100/best.pt --imgsz 640 --save-conf --save-txt --project '/content/drive/MyDrive/people_data' --name 'bbox'

# Plot
Image(filename='/content/drive/MyDrive/people_data/bbox/pet251.jpg', width=416)   # Correct

Image(filename='/content/drive/MyDrive/people_data/bbox/pet246.jpg', width=416) # Wrong

Image(filename='/content/drive/MyDrive/people_data/bbox/pet236.jpg', width=416) # No detection

